# Generated by Django 3.0.7 on 2020-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osonegroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='RecordType',
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'verbose_name_plural': 'recordtypes'},
        ),
        migrations.RenameField(
            model_name='recordtype',
            old_name='typedescription',
            new_name='recorddescription',
        ),
        migrations.RenameField(
            model_name='recordtype',
            old_name='typename',
            new_name='recordname',
        ),
        migrations.AlterModelTable(
            name='recordtype',
            table='recordtype',
        ),
    ]
